# Generated by Django 5.0.3 on 2024-04-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_job_person_alter_genre_name_movie_moviereview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(unique=True),
        ),
    ]
